name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - if: matrix.os == 'ubuntu-latest'
        name: Install g++-10
        run: sudo apt install g++-10
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - if: matrix.os == 'ubuntu-latest'
        name: Build (linux)
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -D CMAKE_CXX_COMPILER=g++-10
      - if: matrix.os == 'windows-latest'
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
      - if: matrix.os == 'windows-latest'
        name: Upload libuv (Windows)
        uses: actions/upload-artifact@v2
        with:
          name: Mycelium-${{ matrix.os }}
          path: |
            build/thirdparty/libuv/${{env.BUILD_TYPE}}/*.dll
      - if: matrix.os == 'windows-latest'
        name: Upload executable (Windows)
        uses: actions/upload-artifact@v2
        with:
          name: Mycelium-${{ matrix.os }}
          path: |
            build/${{env.BUILD_TYPE}}/*.exe
      - if: matrix.os == 'ubuntu-latest'
        name: Upload executable (Linux)
        uses: actions/upload-artifact@v2
        with:
          name: Mycelium-${{ matrix.os }}
          path: |
            build/Mycelium*